import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import { ConfigProvider } from "antd";
import { THEME } from "@/styles/theme";
import { FONT } from "@/styles/font";
import { ToastContainer } from "react-toastify";
import IcWalletProvider from "@/components/provider/ICWalletProvider";

export const metadata: Metadata = {
  title: "ZKGameboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${FONT.className} bg-secondary text-text px-60`}>
        <ConfigProvider
          theme={{
            token: {
              colorText: THEME.TEXT_COLOR,
              colorPrimary: THEME.PRIMARY_COLOR,
              fontFamily: FONT.style.fontFamily
            },
            components: {
              Menu: {
                itemBg: 'transparent',
              },
              Button: {
                defaultBg: THEME.BUTTON_COLOR,
                defaultHoverBg: THEME.BUTTON_HOVER_COLOR,
                defaultActiveBg: THEME.BUTTON_HOVER_COLOR,
                lineWidth: 0,
                fontWeight: 'inherit',
                fontSize: 'inherit',
                colorPrimaryText: THEME.SECONDARY_COLOR,
                colorBgContainerDisabled: THEME.MUTED_COLOR,
              },
              Typography: {
                fontSize: 'inherit',
                colorText: 'currentColor',
              },
              Input: {
                colorBgContainer: THEME.BUTTON_COLOR
              },
              InputNumber: {
                colorBgContainer: THEME.BUTTON_COLOR,
                colorTextPlaceholder: THEME.MUTED_COLOR
              },
              Select: {
                colorBgContainer: THEME.BUTTON_COLOR,
                selectorBg: THEME.BUTTON_COLOR,
              }
            }
          }}
        >
          <IcWalletProvider>
            <Header />
            {children}
          </IcWalletProvider>
          <ToastContainer
            position='bottom-right'
          />
        </ConfigProvider>
      </body>
    </html>
  );
}
